# Generated by Django 4.1.3 on 2022-12-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('experience', models.CharField(max_length=10)),
                ('project', models.CharField(max_length=10)),
                ('worked', models.CharField(max_length=10)),
                ('About_image', models.ImageField(upload_to='AboutImage')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('description', models.TextField()),
                ('Linkedln', models.TextField()),
                ('Dribble', models.TextField()),
                ('Home_image', models.ImageField(upload_to='HomeImage')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_title_E', models.TextField()),
                ('qualification_calender_E', models.IntegerField(max_length=20)),
                ('qualification_title_W', models.TextField()),
                ('qualification_calender_W', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_icon', models.TextField()),
                ('services_title_1', models.CharField(max_length=20)),
                ('services_title_2', models.CharField(max_length=20)),
                ('services_line1', models.TextField()),
                ('services_line2', models.TextField()),
                ('services_line3', models.TextField()),
                ('services_line4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField()),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('skills_name', models.CharField(max_length=50)),
                ('skills_number', models.IntegerField(max_length=3)),
            ],
        ),
    ]
