# Generated by Django 4.1.3 on 2022-12-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='Dribble',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='Linkedln',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skills',
            name='icon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skills',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
