# Generated by Django 4.1.3 on 2022-12-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_home_dribble_alter_home_linkedln_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Github',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
