# Generated by Django 4.1.3 on 2022-12-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_home_github'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skills_name',
            new_name='skills_name1',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skills_number',
        ),
        migrations.AddField(
            model_name='skills',
            name='skills_name2',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='skills_name3',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='skills_name4',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='skills_number1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='skills_number2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='skills_number3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='skills_number4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_calender_E',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_calender_W',
            field=models.IntegerField(),
        ),
    ]
