# Generated by Django 4.1.3 on 2022-12-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_skills_name_skills_skills_name1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='qualification_subtitle_E',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_subtitle_W',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_calender_E',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_calender_W',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_title_E',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_title_W',
            field=models.CharField(max_length=100),
        ),
    ]
