# Generated by Django 4.1.3 on 2023-01-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_qualification_qualification_subtitle_e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='qualification_calender_1E',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_subtitle_1E',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_title_1E',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
