# Generated by Django 4.1.3 on 2023-01-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_qualification_qualification_calender_1e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='qualification_calender_1W',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_calender_2E',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_calender_2W',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_calender_3E',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_subtitle_1W',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_subtitle_2E',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_subtitle_2W',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_subtitle_3E',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_title_1W',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_title_2E',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_title_2W',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_title_3E',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
