# Generated by Django 4.1.3 on 2023-01-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_qualification_qualification_calender_1w_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_calender_1E',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_calender_1W',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_calender_2E',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_calender_2W',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_calender_3E',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_subtitle_1E',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_subtitle_1W',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_subtitle_2E',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_subtitle_2W',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_subtitle_3E',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_title_1E',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_title_1W',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_title_2E',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_title_2W',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_title_3E',
        ),
    ]
